version: '3.5'

services:
  torproxy:
    image: bunseokbot/torproxy:latest
    container_name: torproxy
    networks:
      - darklight

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: darklight:latest
    container_name: scheduler
    environment:
      - CONFIG_FILE=files/config.ini
    networks:
      - darklight
      - database
    depends_on:
      - redis
      - torproxy

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: darklight:latest
    container_name: worker
    command: ["celery", "worker", "-A", "crawler.tasks", "--autoscale=1,7"]
    environment:
      - CONFIG_FILE=files/config.ini
    networks:
      - darklight
      - database
    depends_on:
      - redis
      - torproxy

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - darklight

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: darklight:latest
    container_name: darklight-test
    command: ["python", "-m", "pytest", "-q", "-m", "not integration"]
    environment:
      - CONFIG_FILE=files/config.ini
    depends_on:
      - redis
      - torproxy
      - mariadb
      - elasticsearch
    networks:
      - darklight
      - database

networks:
  darklight:
    name: darklight
  database:
    name: database
